### ISSUE TITLE
Maintainer needed for this plugin

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-input-jms#13]
We would love some help maintaining this plugin. Please comment on this issue if you have experience working with JMS technologies and/or this plugin and are ready to review and merge existing pull requests. Thanks much!

**Comment by JiriKadlcik** [comment]
Hi, I would like to help maintaining the plugin, as I'm actively using it and I will need it in future as well. I've been working with various JMS implementations in last 12 years.

**Comment by acchen97** [comment]
@JiriKadlcik thanks for chiming in! We do have a community maintainer program. If you don't mind, can you please reach out to me at alvin at elastic.co?

**Comment by JiriKadlcik** [comment]
Good news, looks like we eventually have a maintainer.

**Comment by acchen97** [comment]
@JiriKadlcik thanks for volunteering! :)
