### ISSUE TITLE
Help to setup a connection with WebSphere JMS

### ISSUE THREAD

**Issue by ranierimazili** [logstash-plugins/logstash-input-jms#18]
Hello,

I'm trying to connect to a WebSphere JMS. I can connect to it using HermesJMS and below are the steps need to connect to my queue using HermesJMS and then what I tried to connection using logstash-plugin-jms.
Please, I really need help to try to consume messages from this queue and couldn't find any documentation about it.

**Resumed steps to read messages from WebSphere JMS queue on HermesJMS**

1) I have created a folder and named it as "WASJMS" on my client machine and copied the following files from WebSphere to this folder.

com.ibm.ws.sib.client.thin.jms_8.5.0.jar
com.ibm.ws.orb_8.5.0.jar
com.ibm.ws.ejb.thinclient_8.5.0.jar
sas.client.props
ssl.client.props

2) On WebSphere I have key.p12 and trust.p12 files, which I have to convert to jks format so it can be used by Oracle JVM instead of IBM JVM (WebSphere Default JVM)

```
# keytool -v -importkeystore -srckeystore trust.p12 -destkeystore trust.jks -srcstoretype pkcs12 -deststoretype jks -srcstorepass WebAS -deststorepass WebAS_JKS -alias root2 -srckeypass WebAS -destkeypass WebAS_JKS

# keytool -v -importkeystore -srckeystore key.p12 -destkeystore key.jks -srcstoretype pkcs12 -deststoretype jks -srcstorepass WebAS -deststorepass WebAS_JKS -alias default -srckeypass WebAS -destkeypass WebAS_JKS
```

Then I copied the new files (key.jks and trust.jks) to my client folder (WASJMS)

3) Some changes was made on ssl.client.props and sas.client.props file to setup jks files path, passwords and set it to read SUN(Oracle) type. The main piece of these files are below:

**ssl.client.props**
```
com.ibm.ssl.alias=DefaultSSLSettings
com.ibm.ssl.protocol=SSL
com.ibm.ssl.securityLevel=HIGH
com.ibm.ssl.trustManager=SunX509
com.ibm.ssl.keyManager=SunX509
com.ibm.ssl.contextProvider=SunJSSE
com.ibm.ssl.enableSignerExchangePrompt=gui

# KeyStore information
com.ibm.ssl.keyStoreName=ClientDefaultKeyStore
com.ibm.ssl.keyStore=C:/Users/ranieri/WASJMS/key.jks
com.ibm.ssl.keyStorePassword=WebAS_JKS
com.ibm.ssl.keyStoreType=JKS
com.ibm.ssl.keyStoreProvider=SUN
com.ibm.ssl.keyStoreFileBased=true

# TrustStore information
com.ibm.ssl.trustStoreName=ClientDefaultTrustStore
com.ibm.ssl.trustStore=C:/Users/ranieri/WASJMS/trust.jks
com.ibm.ssl.trustStorePassword=WebAS_JKS
com.ibm.ssl.trustStoreType=JKS
com.ibm.ssl.trustStoreProvider=SUN
com.ibm.ssl.trustStoreFileBased=true
com.ibm.ssl.trustStoreReadOnly=false
```

**sas.client.props**
```
com.ibm.CORBA.authenticationTarget=BasicAuth
com.ibm.CORBA.authenticationRetryEnabled=true
com.ibm.CORBA.authenticationRetryCount=3
com.ibm.CORBA.validateBasicAuth=true
com.ibm.CORBA.securityServerHost=bpm857
com.ibm.CORBA.securityServerPort=9810
com.ibm.CORBA.loginTimeout=300
com.ibm.CORBA.loginSource=properties

# RMI/IIOP user identity
com.ibm.CORBA.loginUserid=myuser
com.ibm.CORBA.loginPassword=mypassword
```

4) Then, I changed hermes.bat file to use my ssl.client.props and sas.client.props on startup, pasting the following files before last line.

```
set SSL_RMI_DEFS= ^
-Dcom.ibm.SSL.ConfigURL="file:/C:/Users/ranieri/WASJMS/ssl.client.props" ^
-Dcom.ibm.CORBA.ConfigURL="file:/C:/Users/ranieri/WASJMS/sas.client.props" 
set HERMES_OPTS=%HERMES_OPTS% %SSL_RMI_DEFS%
```

5) Then I opened HermesJMS, created a new session which I named as was855 and on providers tab I've created a new group (was855sib) and added all jars needed (the 3 jars files I mentioned in step 1)

![providers](https://cloud.githubusercontent.com/assets/15436207/23583775/a2b654b4-012c-11e7-9b87-8f2ca87ea8ef.png)

6) Then, back in sessions tab I choose hermes.JNDIQueueConnectionFactory as class and choose was855sib to use their jars dependencies. After that, I've added 3 properties and set their values as below:

```
binding: jms/RanieriConnectionFactory
initialContextFactory: com.ibm.websphere.naming.WsnInitialContextFactory
providerURL: iiop://bpm857:9810
```

Also, I have informed username and password fields, this is the WebSphere user and pass that has permission to read the queue.

![sessions](https://cloud.githubusercontent.com/assets/15436207/23583778/b02721fa-012c-11e7-841a-1857279c628b.png)

7) That's all. After this setup all I needed to do is right click on the created session and choose "Discover" option, so it listed all JMS queues and could I choose my jms/RanieriQueue

![jmsranieriqueuemessages](https://cloud.githubusercontent.com/assets/15436207/23583782/bb1bbfa8-012c-11e7-9ce6-07b484e3d965.png)

That's it. I want to read the same queue (jms/RanieriQueue) using logstash-input-jms plugin and I've tried using the following configuration.

**logstash.conf**
```
input { 
	jms {
		yaml_file => "C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/config/jms.yml"
		yaml_section => "websphere"
		include_header => true
		include_properties => true
		include_body => true
		use_jms_timestamp => false
		destination => "jms/RanieriQueue"
		interval => 3
		runner => async
	}
}
output {
  stdout { codec => rubydebug }
}
```

**jms.yml**
```
# JMS
websphere:
  # Connect to a remote WebSphere JMS Queue
 :jndi_name: jms/RanieriConnectionFactory
 :jndi_context: 
   java.naming.factory.initial: com.ibm.websphere.naming.WsnInitialContextFactory
   java.naming.provider.url: iiop://bpm857:9810
   java.naming.factory.url.pkgs: com.ibm.ws.naming
   java.naming.security.principal: bpmadmin
   java.naming.security.credentials: bpmadmin
 :require_jars:
   - C:\Users\ranieri\WASJMS\com.ibm.ws.ejb.thinclient_8.5.0.jar
   - C:\Users\ranieri\WASJMS\com.ibm.ws.orb_8.5.0.jar
   - C:\Users\ranieri\WASJMS\com.ibm.ws.sib.client.thin.jms_8.5.0.jar
```

Also, I've changed setup.bat inside logstash-5.2.2/bin to load ssl.client.props and sas.client.props adding the following lines:

```
SET JAVA_OPTS=%JAVA_OPTS% -Dcom.ibm.SSL.ConfigURL=file:/C:/Users/ranieri/WASJMS/ssl.client.props
SET JAVA_OPTS=%JAVA_OPTS% -Dcom.ibm.CORBA.ConfigURL=file:/C:/Users/ranieri/WASJMS/sas.client.props
```

When I try to start logstash I'm receiving the following error message.

`22:38:29.931 [[main]<jms] WARN  logstash.inputs.jms - JMS Consumer died {:exception=>javax.jms.JMSSecurityException: CWSIA0006E: The authorization for the supplied user name was not successful., :backtrace=>["com.ibm.ws.sib.api.jms.impl.JmsManagedConnectionFactoryImpl.createConnection(com/ibm/ws/sib/api/jms/impl/JmsManagedConnectionFactoryImpl.java:186)", "com.ibm.ws.sib.api.jms.impl.JmsManagedConnectionFactoryImpl.createConnection(com/ibm/ws/sib/api/jms/impl/JmsManagedConnectionFactoryImpl.java:138)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "RUBY.initialize(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/jruby-jms-1.2.0-java/lib/jms/connection.rb:204)", "RUBY.start(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/jruby-jms-1.2.0-java/lib/jms/connection.rb:50)", "RUBY.run_async(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-input-jms-3.0.0-java/lib/logstash/inputs/jms.rb:226)", "RUBY.run(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-input-jms-3.0.0-java/lib/logstash/inputs/jms.rb:257)", "RUBY.inputworker(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:449)", "RUBY.start_input(C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:443)", "java.lang.Thread.run(java/lang/Thread.java:745)"]}`

Any ideas of where is my mistake? 
Thanks

P.S: I also have a java code that can connect to this queue and read the messages, let me know if you think java code can help you to understand where is the problem.

**Comment by ranierimazili** [comment]
I made it. The main problem was that I was using jndi name on destination parameter but I should use queue name. To connect using Java I can connect only using jndi name but to make it work with logstash-input-jms plugin I had to change it by queue name.

Here are my configuration files.

**logstash.conf**
```
input { 
	jms {
		yaml_file => "C:/Users/ranieri/Downloads/logstash-5.2.2/logstash-5.2.2/config/jms.yml"
		yaml_section => "websphere"
		include_header => true
		include_properties => true
		include_body => true
		use_jms_timestamp => false
		destination => "RanieriQueueDestination"
		interval => 3
		runner => async
	}
}
output {
  stdout { codec => rubydebug }
}
```

**jms.yml**
```
# JMS
websphere:
  # Connect to a remote WebSphere JMS Queue
 :username: myuser
 :password: mypass
 :jndi_name: jms/RanieriConnectionFactory
 :jndi_context:
   java.naming.factory.initial: com.ibm.websphere.naming.WsnInitialContextFactory
   java.naming.provider.url: iiop://bpm857:9810
   java.naming.security.principal: myuser
   java.naming.security.credentials: mypass
 :require_jars:
   - C:\Users\ranieri\WASJMS\com.ibm.ws.ejb.thinclient_8.5.0.jar
   - C:\Users\ranieri\WASJMS\com.ibm.ws.orb_8.5.0.jar
   - C:\Users\ranieri\WASJMS\com.ibm.ws.sib.client.thin.jms_8.5.0.jar
```

**Comment by chmorfop** [comment]
Hi rania I have a similar problem. .Any suggestions would be greatly appreciated!!!

 I have installed Weblogic 12.2.1 and the latest Logstash 7.5.2 version as well as the jms plugin v3.1.2. I am struggling with the jms plug in and I have already set the .conf and .yml, but it doesn't work!
In the Destination field the documentation and the examples suggest no JNDI name, just the queue or topic name!!!

The input of the jms.conf :
input {
jms { pub_sub => false
include_header => false
include_properties => false
include_body => true
use_jms_timestamp => false
yaml_file => "/home/chris/Downloads/logstash-7.5.2/config/jms.yml"
yaml_section => "weblogic"
destination => "DemoQ"
}
}

The yml :

weblogic:
:jndi_name: jms/DemoCF
:jndi_context:
java.naming.factory.initial: weblogic.jndi.WLInitialContextFactory
java.naming.provider.url: t3://localhost:7001
java.naming.factory.url.pkgs: javax.naming:javax.jms
java.naming.security.principal: weblogic
java.naming.security.credentials: *****!
:require_jars:
- /home/chris/Downloads/wlogic/fmw_12.2.1.0.0_wls_quick_Disk1_1of1/wls12210/wlserver/server/lib/wlthint3client.jar
- /home/chris/Downloads/wlogic/fmw_12.2.1.0.0_wls_quick_Disk1_1of1/wls12210/wlserver/server/lib/wljmsclient.jar
- /home/chris/Downloads/wlogic/fmw_12.2.1.0.0_wls_quick_Disk1_1of1/wls12210/wlserver/server/lib/wlclient.jar

and the ouput of the Logstash :

[2020-01-31T14:50:10,284][WARN ][logstash.inputs.jms ][main] JMS Consumer Died {:exception=>"Java::WeblogicJmsCommon::JMSException", :exception_message=>"[JMSExceptions:045101]The destination name passed to the createTopic or createQueue "DemoQ" is invalid. If the destination name does not contain a "/" character, then it must be the name of a distributed destination that is available in the cluster to which the client is attached. If it does contain a "/" character, then the string before the "/" must be the name of a JMS server or a ".". The string after the "/" is the name of a the desired destination. If the "./" version of the string is used then any destination with the given name on the local WebLogic Server instance
