### ISSUE TITLE
Adding support for Topic/durable subscription  

### ISSUE THREAD

**Issue by grikag** [logstash-plugins/logstash-input-jms#23]
Please help with adding support for Topic/durable subscription
I believe "jruby-jms" has support for durable subscribers
Unfortunately, there is no "durable name" attribute for "destination name" (re: pup_sub => true)
Thanks
GK

**Comment by andrewvc** [comment]
Would you be interested in patching this yourself?

**Comment by d0nski** [comment]
Was this ever implemented?  If not if someone can point me in the direction I'd be interested in doing it

**Comment by robbavey** [comment]
Resolved by #35
