### ISSUE TITLE
Oracle AQ buffered messages support

### ISSUE THREAD

**Issue by i-kovalyov** [logstash-plugins/logstash-input-jms#26]
Hello.

Oracle AQ has two kinds of messages: persistent and buffered messages. 

Persistent messages are supported by jms plugin but buffered messages support require usage of Oracle  JMS extension APIs.

Currently jms plugin doesn't support Oracle AQ buffered messages.

What about adding support of Oracle AQ buffered messages into jms plugin? 
WilI you accept my pull request with this enhancement?
What about adding boolean config option "oracle_aq_buffered_messages" with default false value?

**Comment by jsvd** [comment]
Hi @i-kovalyov, thanks for taking interest in improving this plugin, I'll certainly review the PR and help get it merged and released.

As for the change itself, I have noticed [your contribution to jruby-jms](https://github.com/reidmorrison/jruby-jms/blob/2b0ea338e251a8ae3e24fba97a5b4809293ae865/lib/jms/message_consumer.rb) a few weeks ago, and I agree a flag to enable it makes sense.

**Comment by robbavey** [comment]
This was resolved a while ago by #28
