### ISSUE TITLE
refactor shutdown sequence to use plugin.stop

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-jms#6]
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

**Comment by gjelu** [comment]
I have created a fork and refactored it: https://github.com/gjelu/logstash-input-jms/commit/e8207dd898b3817827bc635ea90d061547c38ec2

added calls to stop, close, stop? 
removed ShutdownSignal exception
make use of the new Event API (get, set), see issue #14

**Comment by JiriKadlcik** [comment]
Used gjelu's commit and and merged as https://github.com/logstash-plugins/logstash-input-jms/pull/15
